import '@ui/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import logo_jupiter from './assets/imgs/jupiter_logo.png'
const inter = Inter({ subsets: ['latin'] });
import { ThemeProvider } from "@ui/components/theme-provider"

export const metadata: Metadata = {
  icons: { icon: logo_jupiter.src },
  title: 'Júpiter',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
    <head />
    <body className={inter.className}>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}
      </ThemeProvider>
    </body>
  </html>
  );
}
